# Generated by Django 6.0.5 on 2026-05-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_product_file_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(default=None, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
