# Generated by Django 6.0.5 on 2026-05-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_alter_product_file_alter_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
    ]
